name: CI

on:
  pull_request:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install package
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run lint

      - name: Build test
        run: yarn run build

  functions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./functions

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install package
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn run lint
